import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    // The shadcn-svelte component tree under src/lib/components/ui/ is
    // vendored (generated by the shadcn-svelte CLI, not hand-authored),
    // and node_modules/svelte build output aren't ours to lint either.
    ignores: ["node_modules/", "**/static/", "src/lib/components/ui/**"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.es2021 },
    },
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
  },
  {
    rules: {
      // Svelte 5 runes ($state, $derived, $props, ...) are compiler
      // intrinsics, not real unused vars/undefined-globals.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
);
